version: '3.8'

services:
    app:
        build: ./
        command: ./wait-for-postgres.sh db ./main
        ports:
            - "9000:9000"
        depends_on:
            - db
        environment:
            - DB_PASSWORD=postgres
    db:
        restart: always
        image: postgres:14.1-alpine
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        ports:
            - "5000:5432"
        volumes:
            - db:/var/lib/postgresql/data
volumes:
    db: 
        driver: local
